    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <!-- Define el autor del documento -->
    <meta name="author" content="Francisco Antonio Murillo Pacheco" />
    <!-- Define el programa con el que se ha generado el documento -->
    <meta name="generator" content="NetBeans 11.1" />
    <!-- Define el copyright del documento -->
    <meta name="copyright" content="DWES repaso Francisco Antonio Murillo Pacheco 2020" />
    <!-- Define el comportamiento de los buscadores -->
    <meta name="robots" content="index, follow" />
    <!-- Define las palabras claves del contenido del documento -->
    <meta name="keywords" content="GestionSesionesFranciscoAMP" />
    <!-- Define una breve descripción del sitio -->
    <meta name="description" content="Gestión usuarios en sesión." />
